{{- if .Values.metrics.serviceMonitor.enabled }}
{{- $integrations := list }}
{{- if .Values.integrations.datadog.enabled }}{{ $integrations = append $integrations "datadog-controller" }}{{ end }}
{{- if .Values.integrations.openkruise.enabled }}{{ $integrations = append $integrations "openkruise-controller" }}{{ end }}
{{- if .Values.integrations.environment.enabled }}{{ $integrations = append $integrations "environment-controller" }}{{ end }}
{{- range $integrations }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ . }}
  namespace: {{ default $.Values.namespace $.Values.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "kuberik.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ . }}
    {{- with $.Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ . }}
      control-plane: controller-manager
  endpoints:
    - port: https
      scheme: https
      interval: {{ $.Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ $.Values.metrics.serviceMonitor.scrapeTimeout }}
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- end }}
{{- end }}
